name: Generate Snake Animation

on:
  schedule:
    # Runs every 6 or 12 hours - adjust as you like
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allows manual triggering from the Actions tab

permissions:
  contents: write # Needed to push the generated files to the output branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a recent version of checkout

      - name: Generate Snake animation
        uses: Platane/snk@v3 # Use v3 of the snake action
        id: snake-animation # Optional ID for the step
        with:
          github_user_name: ${{ github.repository_owner }} # Dynamically gets your username
          # Define the output files.
          # The palette option creates a dark mode version.
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            # You can also output a GIF if desired:
            # dist/github-contribution-grid-snake.gif

      - name: Push generated animation to output branch
        uses: crazy-max/ghaction-github-pages@v4 # Use a recent version for deploying
        with:
          target_branch: output # The branch where the SVG files will be committed
          build_dir: dist # The directory containing the generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token to allow pushing to the branch
